/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export interface Logs {
  ClientHost: string;
  DownstreamContentSize: number;
  DownstreamStatus: number;
  Duration: string;
  id: Generated<number | null>;
  RequestMethod: string;
  RequestPath: string | null;
  'request_User-Agent': string | null;
  'request_X-Forwarded-Proto': string | null;
  RetryAttempts: string;
  ServiceName: string | null;
  StartUTC: string;
  time: string;
}

export interface DB {
  logs: Logs;
}
